import Image from "next/image";

export default function Home() {
  return (
    <main className="">
      <div className="flex flex-col items-center justify-between">
        <div className="h-[full] w-full">
          <Image
            src="https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?q=80&w=2671&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
            alt="model"
            width={1920}
            height={1080}
            style={{ objectFit: "contain" }}
          />
        </div>
        <div className="">
          This is Start! AVIE MUAH IS AN ARTISAN CLOTHING BRAND BASED ON THE
          UNIQUE TASTES OF ITS FOUNDER.THE BRAND USES NATURAL FIBERS TO CREATE
          COMFORTABLE CLOTHING FOR A WIDE VARIETY OF LIFESTYLES.AVIE MUAH VALUES
          THE WORK OF INDEPENDENT EMERGING DESIGNERS WHO HELP TO OFFER HIGH
          QUALITY.HANDMADE GARMENTS FOR EVERY CUSTOMER. AVIE MUAH IS AN ARTISAN
          CLOTHING BRAND BASED ON THE UNIQUE TASTES OF ITS FOUNDER. This is
          Start! AVIE MUAH IS AN ARTISAN CLOTHING BRAND BASED ON THE UNIQUE
          TASTES OF ITS FOUNDER.THE BRAND USES NATURAL FIBERS TO CREATE
          COMFORTABLE CLOTHING FOR A WIDE VARIETY OF LIFESTYLES.AVIE MUAH VALUES
          THE WORK OF INDEPENDENT EMERGING DESIGNERS WHO HELP TO OFFER HIGH
          QUALITY.HANDMADE GARMENTS FOR EVERY CUSTOMER. AVIE MUAH IS AN ARTISAN
          CLOTHING BRAND BASED ON THE UNIQUE TASTES OF ITS FOUNDER. This is
          Start! AVIE MUAH IS AN ARTISAN CLOTHING BRAND BASED ON THE UNIQUE
          TASTES OF ITS FOUNDER.THE BRAND USES NATURAL FIBERS TO CREATE
          COMFORTABLE CLOTHING FOR A WIDE VARIETY OF LIFESTYLES.AVIE MUAH VALUES
          THE WORK OF INDEPENDENT EMERGING DESIGNERS WHO HELP TO OFFER HIGH
          QUALITY.HANDMADE GARMENTS FOR EVERY CUSTOMER. AVIE MUAH IS AN ARTISAN
          CLOTHING BRAND BASED ON THE UNIQUE TASTES OF ITS FOUNDER.
        </div>
      </div>
    </main>
  );
}
